pipeline {
  //agent any
  agent {label 'Ecs-agent'}  
  tools {nodejs "node"}
    
  stages {
        
    stage('Git') {
      steps {
        script {
           git credentialsId: 'wahaj123', url: 'https://github.com/wahaj123/Jenkins-autoscaling'
          }
      }
    }
     
    stage('Build') {
      steps {
        sh 'pwd'
        // sh 'npm intstall'
        // sh 'npm install express'
      }
    }      
     stage('Deployment') {
        steps {
            script {
                sshPublisher(publishers: [
                    sshPublisherDesc(
                        configName: 'ec2-user',
                        transfers: [
                            sshTransfer(
                                sourceFiles: "app.js",
                                execCommand: "npm install; npm install express; nohup node app.js &",
                                // remoteDirectory: '/home/ec2-user/jenkins'  
                            )
                        ],
                        usePromotionTimestamp: false,
                        useWorkspaceInPromotion: false,
                        verbose: false
                    )]
                )
            }
        }
    }       
  }
}
